package de.raindancer.modules.farmworld.service;

import de.raindancer.core.ui.bossbar.BarPriority;
import de.raindancer.core.ui.bossbar.BarStyle;
import de.raindancer.core.ui.bossbar.BossBars;
import de.raindancer.core.ui.effect.Cues;
import de.raindancer.core.ui.effect.Effects;
import de.raindancer.core.ui.messages.Messages;
import de.raindancer.core.world.time.Times;
import de.raindancer.modules.farmworld.FarmWorldSettings;
import de.raindancer.modules.farmworld.model.FarmWorldView;
import de.raindancer.modules.farmworld.rules.NoticeRule;
import de.raindancer.modules.farmworld.store.FarmWorldCatalogue;
import net.kyori.adventure.audience.Audience;
import net.kyori.adventure.bossbar.BossBar;

import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Telling the server a farm world is about to be thrown away — and that it has been.
 *
 * <h2>Why this exists beside Core's own timer</h2>
 * Core regenerates a farm world when its time is up and says one line to whoever was standing in it. This
 * does not regenerate anything and must not: two timers both deciding a farm world is due is two
 * regenerations racing, and the loser deletes a folder the winner has already recreated. What this does is
 * watch the same clock Core watches and speak before it acts.
 *
 * <p>The division is exact. Core knows how to delete three worlds; it does not know what this server wants
 * to say. This knows what to say and has no idea how to delete anything.
 *
 * <h2>Why it also announces afterwards</h2>
 * Because the last warning goes out a minute before, and a minute later somebody who was walking back
 * finds their tunnel gone with nothing having marked the moment. Detected by the recorded time changing
 * rather than by being told: the module is not what does it, so being told would mean Core calling back
 * into a module that may not be loaded.
 *
 * <h2>What is remembered, and why here rather than in the rule</h2>
 * One entry per farm world: the largest warning already given, and the time it was last made. The rule
 * decides and remembers nothing — there is one rule for the whole server and it is asked about each farm
 * world in turn, so a rule that remembered would announce each warning once across all of them and
 * silently skip the rest.
 */
public final class NoticeService implements IFarmWorldService {

    private final FarmWorldCatalogue catalogue;
    private final Messages messages;
    /** Everybody, as one audience. The server itself on a live server; a collector in a test. */
    private final Audience everybody;

    /** The largest warning already given for each farm world, by name. */
    private final Map<String, Duration> announced = new ConcurrentHashMap<>();

    /**
     * How long each farm world had left when it was last looked at.
     *
     * <p>Which is how "it has just been made again" is noticed: the time left jumps from nearly nothing
     * back to the whole period. Compared against the previous reading rather than against a recorded
     * timestamp, because a farm world regenerated by hand and one regenerated on its schedule look
     * identical from here — and both want the same sentence.
     */
    private final Map<String, Duration> lastSeen = new ConcurrentHashMap<>();

    /**
     * The last minutes, as a bar above the hotbar.
     *
     * <p>Core's, and the reason it belongs there rather than here: a player may have three bars at most and
     * several plugins want one, so who wins is arbitration nobody can do alone. {@code showShared} takes the
     * audience on every call, which is exactly the shape this needs — walk out of the farm world and the bar
     * goes with the world you left.
     */
    private final BossBars bars;

    /**
     * The sounds, asked for by meaning rather than by name.
     *
     * <p>Core's, so a server that decides a countdown should sound different rebinds one cue and every plugin's
     * countdown changes with it. Also why nothing here names a {@code Sound}: a plugin that did would be the one
     * whose ticking is the only thing on the server that did not follow.
     */
    private final Effects effects;

    /** What the bar is registered under, so Core can say which plugin owns it. */
    private static final String OWNER = "RainsFarmWorlds";

    /**
     * How long before the end the bar appears.
     *
     * <p>Five minutes. Chat is where a warning goes so that somebody planning a trip sees it; a bar is for
     * somebody who is <em>in</em> the farm world right now, has probably scrolled chat past the notice, and needs
     * the number in front of them while they decide what to carry out. Any longer and it is furniture.
     */
    private static final Duration BAR_WINDOW = Duration.ofMinutes(5);

    private volatile NoticeRule rule;

    /**
     * @param bars    Core's boss bars; null for a host that has none, which leaves the chat notices working on
     *                their own rather than taking the whole timer down
     * @param effects Core's sounds, same reasoning — a missing sound must not cost anybody their warning
     */
    public NoticeService(FarmWorldCatalogue catalogue, Messages messages, Audience everybody,
                         BossBars bars, Effects effects, FarmWorldSettings settings) {
        this.catalogue = catalogue;
        this.messages = messages;
        this.everybody = everybody;
        this.bars = bars;
        this.effects = effects;
        settings(settings);
    }

    @Override
    public void settings(FarmWorldSettings fresh) {
        // Rebuilt rather than told, because the lead time is the only thing the rule holds and a rule you
        // can change is one two callers can see differently.
        this.rule = new NoticeRule(fresh.warnLead());
    }

    /** The warnings that will be given, for the config page and the manual. */
    public NoticeRule warnings() {
        return rule;
    }

    /**
     * One look at every farm world. Called once a second.
     *
     * <p>Cheap on purpose: it reads what is already in memory, asks a rule, and — only for a farm world inside
     * its last five minutes — asks the server who is standing in it. Nothing here touches the disk.
     *
     * <p>Once a second rather than once in twenty, and for two reasons that both showed up as soon as there was
     * a bar. A countdown bar that moves in twenty-second steps reads as a broken bar, and the last notice before
     * three worlds are deleted arriving up to twenty seconds late is the difference between useful and cruel.
     */
    public void check() {
        for (FarmWorldView farm : catalogue.all()) {
            look(farm);
        }
        // Farm worlds that have been forgotten since the last look. Left behind, the map grows by an entry
        // for every farm world that has ever existed — small, but it is also a stale "I already warned
        // about this" waiting for somebody to create a farm world with the same name again.
        announced.keySet().removeIf(name -> catalogue.byName(name).isEmpty());
        lastSeen.keySet().removeIf(name -> catalogue.byName(name).isEmpty());
    }

    private void look(FarmWorldView farm) {
        Duration left = farm.untilRegenerated().orElse(null);
        Duration before = lastSeen.get(farm.name());
        lastSeen.put(farm.name(), left == null ? Duration.ZERO : left);

        if (madeAgain(before, left)) {
            announced.remove(farm.name());
            clearBar(farm);
            messages.send(everybody, "farmworlds.made-again", "name", farm.name());
            return;
        }
        if (!farm.isScheduled()) {
            announced.remove(farm.name());
            clearBar(farm);
            return;
        }
        if (rule.hasStartedOver(left)) {
            // A new countdown: created, regenerated, or its schedule lengthened. Forgetting what was said
            // about the last one is what lets this one be warned about at all.
            announced.remove(farm.name());
        }
        Optional<Duration> due = rule.dueNow(left, announced.get(farm.name()));
        due.ifPresent(lead -> {
            announced.put(farm.name(), lead);
            // The lead is what is recorded; what is *said* is the time actually left. The two differ by a second
            // in the ordinary case and by minutes when a look was missed, and it is the second case that makes
            // this the right way round: announcing the lead there would tell the server fifteen minutes when
            // there were ninety seconds.
            messages.send(everybody, "farmworlds.warning",
                    "name", farm.name(), "time", Times.describe(left));
        });
        countdown(farm, left);
    }

    /**
     * The bar and the ticking, for whoever is standing in the farm world.
     *
     * <h2>Why the people inside get more than the server does</h2>
     * A chat notice is for somebody deciding whether to set off. Somebody who is already there has a different
     * problem: they are three hundred blocks down a tunnel with a full inventory, they have almost certainly
     * scrolled the notice past, and what they need is the number in front of them while they decide what to carry
     * out. That is a bar, not a line.
     *
     * <h2>The sound, and why it is only at the end</h2>
     * A tick every second for five minutes is not urgency, it is an alarm clock nobody can switch off — and Core
     * suppresses repeats anyway, so most of them would be swallowed. So: once on each of the last ten seconds,
     * which is the shape everybody already knows from a countdown, and {@code COUNTDOWN_DONE} on the last one.
     * Both cues are Core's, asked for by meaning: a server that rebinds what a countdown sounds like rebinds
     * this along with every other plugin's.
     */
    private void countdown(FarmWorldView farm, Duration left) {
        if (bars == null || left == null || left.compareTo(BAR_WINDOW) > 0) {
            clearBar(farm);
            return;
        }
        List<UUID> inside = catalogue.playersIn(farm);
        if (inside.isEmpty()) {
            // Empty ends the bar in Core, which is the same call — but clearBar says what is meant.
            clearBar(farm);
            return;
        }

        long secondsLeft = Math.max(0, left.getSeconds());
        float howFarThrough = (float) secondsLeft / BAR_WINDOW.getSeconds();
        bars.showShared(OWNER, farm.name(), inside,
                BarStyle.of(messages.get("farmworlds.bar",
                                "name", farm.name(), "time", Times.brief(left)))
                        .progress(Math.max(0f, Math.min(1f, howFarThrough)))
                        // Red for the last minute, yellow before it. The colour is the part somebody notices
                        // without reading, which is the whole reason a bar beats a line here.
                        .colour(secondsLeft <= 60 ? BossBar.Color.RED : BossBar.Color.YELLOW),
                // CRITICAL because it is exactly what that priority is for: the server is about to do something
                // to them, and it is going to happen whether or not they have finished reading.
                BarPriority.CRITICAL);

        if (effects != null && secondsLeft <= TICKING_STARTS_AT && secondsLeft > 0) {
            effects.playForAll(inside,
                    secondsLeft <= 1 ? Cues.COUNTDOWN_DONE : Cues.COUNTDOWN);
        }
    }

    /** How many seconds from the end the ticking starts. Ten, because that is the shape people know. */
    private static final long TICKING_STARTS_AT = 10;

    private void clearBar(FarmWorldView farm) {
        if (bars != null) {
            bars.clearShared(OWNER, farm.name());
        }
    }

    /**
     * Whether a farm world was made again between two looks.
     *
     * <p>The time left having grown. Not "left is now null" — that is what a farm world <em>due</em> looks
     * like, and announcing then would announce it once every twenty seconds for as long as it stayed due,
     * which happens whenever a regeneration cannot be completed.
     *
     * <p>Requires a previous reading that was small: without that, every farm world would be announced as
     * newly made on the first look after a restart, which is a server telling everybody their farm world
     * has been wiped when nothing has happened at all.
     */
    private static boolean madeAgain(Duration before, Duration now) {
        return before != null && now != null && now.compareTo(before) > 0;
    }

    /** Forgets what was said about one farm world. For a farm world being taken off the list. */
    public void forget(String name) {
        if (name != null) {
            announced.remove(name);
            lastSeen.remove(name);
        }
    }

    @Override
    public String describe() {
        return "warning the server before a farm world is thrown away";
    }
}
