package de.raindancer.modules.homes;

import de.raindancer.modules.homes.store.LegacyHomesFile;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Reading the homes an upgrading server already has.
 *
 * <h2>Why this is the most important test in the module</h2>
 * Because the failure is somebody losing the home they built a base around, and it is silent: the
 * plugin starts, the list is empty, and the file it was reading is still sitting on disk looking
 * correct. There is no earlier migration in this plugin to imitate — the format has never changed —
 * so this is written against a fixture taken from the shape the old {@code HomeStore.write} produced,
 * field for field.
 *
 * <p>The fixture is deliberately <em>not</em> generated by this module's own writer. A fixture that
 * agrees with today's writer proves only that the writer agrees with itself.
 */
class LegacyHomesFileTest {

    private static final UUID ALICE = UUID.fromString("11111111-2222-3333-4444-555555555555");
    private static final UUID BOB = UUID.fromString("66666666-7777-8888-9999-000000000000");

    @TempDir
    Path directory;

    /**
     * Exactly what the old plugin wrote.
     *
     * <p>Down to the details that matter: {@code yaw}/{@code pitch} stored as doubles although the
     * record held floats, {@code created} as epoch millis, and {@code icon} present on one home and
     * absent on the other — the old writer only wrote it when non-blank.
     */
    private Path fileWith(String body) throws IOException {
        Path file = directory.resolve("homes.yml");
        Files.writeString(file, body);
        return file;
    }

    private Path twoPlayers() throws IOException {
        return fileWith("""
                players:
                  11111111-2222-3333-4444-555555555555:
                    name: Alice
                    homes:
                      home:
                        world: world
                        x: 121.5
                        y: 64.0
                        z: -310.5
                        yaw: 90.0
                        pitch: -12.0
                        created: 1700000000000
                        icon: RED_BED
                      mine:
                        world: world_nether
                        x: 10.0
                        y: 32.0
                        z: 20.0
                        yaw: 0.0
                        pitch: 0.0
                        created: 1700000001000
                  66666666-7777-8888-9999-000000000000:
                    name: Bob
                    homes:
                      base:
                        world: world
                        x: 1.0
                        y: 2.0
                        z: 3.0
                        yaw: 0.0
                        pitch: 0.0
                        created: 1700000002000
                """);
    }

    @Nested
    @DisplayName("reading what is there")
    class Reading {

        @Test
        @DisplayName("every home of every player is found")
        void everythingIsRead() throws IOException {
            List<LegacyHomesFile.Entry> found = LegacyHomesFile.read(twoPlayers());

            assertThat(found).hasSize(3);
            assertThat(found).extracting(LegacyHomesFile.Entry::name)
                    .containsExactlyInAnyOrder("home", "mine", "base");
        }

        @Test
        @DisplayName("each home keeps its owner")
        void ownersAreKept() throws IOException {
            List<LegacyHomesFile.Entry> found = LegacyHomesFile.read(twoPlayers());

            assertThat(found).filteredOn(entry -> entry.name().equals("base"))
                    .singleElement()
                    .extracting(LegacyHomesFile.Entry::owner)
                    .isEqualTo(BOB);
            assertThat(found).filteredOn(entry -> entry.owner().equals(ALICE)).hasSize(2);
        }

        @Test
        @DisplayName("every coordinate, the world and the facing survive exactly")
        void thePlaceSurvives() throws IOException {
            LegacyHomesFile.Entry home = LegacyHomesFile.read(twoPlayers()).stream()
                    .filter(entry -> entry.name().equals("home"))
                    .findFirst().orElseThrow();

            assertThat(home.world()).isEqualTo("world");
            assertThat(home.x()).isEqualTo(121.5);
            assertThat(home.y()).isEqualTo(64.0);
            assertThat(home.z()).isEqualTo(-310.5);
            assertThat(home.yaw())
                    .as("stored as a double by the old writer and read back as a float — a home that "
                            + "arrives facing the wrong way is one people notice immediately")
                    .isEqualTo(90.0f);
            assertThat(home.pitch()).isEqualTo(-12.0f);
        }

        @Test
        @DisplayName("the icon is kept when there was one")
        void theIconIsKept() throws IOException {
            LegacyHomesFile.Entry home = LegacyHomesFile.read(twoPlayers()).stream()
                    .filter(entry -> entry.name().equals("home"))
                    .findFirst().orElseThrow();

            assertThat(home.icon()).isEqualTo("RED_BED");
        }

        @Test
        @DisplayName("a home with no icon is read, not skipped")
        void noIconIsFine() throws IOException {
            // The old writer omitted the key entirely rather than writing a blank, so most homes on
            // a real server have no icon line at all. Reading that as "broken entry" would drop the
            // majority of them.
            LegacyHomesFile.Entry mine = LegacyHomesFile.read(twoPlayers()).stream()
                    .filter(entry -> entry.name().equals("mine"))
                    .findFirst().orElseThrow();

            assertThat(mine.icon()).isEmpty();
            assertThat(mine.world()).isEqualTo("world_nether");
        }

        @Test
        @DisplayName("when it was made is kept")
        void theDateIsKept() throws IOException {
            LegacyHomesFile.Entry home = LegacyHomesFile.read(twoPlayers()).stream()
                    .filter(entry -> entry.name().equals("home"))
                    .findFirst().orElseThrow();

            assertThat(home.createdAt()).isEqualTo(1_700_000_000_000L);
        }

        @Test
        @DisplayName("the last-known player name is kept, for whoever reads the file by hand")
        void theOwnerNameIsKept() throws IOException {
            assertThat(LegacyHomesFile.read(twoPlayers()))
                    .filteredOn(entry -> entry.owner().equals(ALICE))
                    .allSatisfy(entry -> assertThat(entry.ownerName()).isEqualTo("Alice"));
        }
    }

    @Nested
    @DisplayName("a file that is not quite right")
    class Broken {

        @Test
        @DisplayName("no file at all is nothing to import, not a failure")
        void noFile() {
            assertThat(LegacyHomesFile.read(directory.resolve("nothing.yml"))).isEmpty();
            assertThat(LegacyHomesFile.read(null)).isEmpty();
        }

        @Test
        @DisplayName("an empty file is nothing to import")
        void emptyFile() throws IOException {
            assertThat(LegacyHomesFile.read(fileWith(""))).isEmpty();
            assertThat(LegacyHomesFile.read(fileWith("players:\n"))).isEmpty();
        }

        @Test
        @DisplayName("a key that is not a uuid is stepped over, and the rest still loads")
        void aBadIdIsSkipped() throws IOException {
            // The old loader did exactly this and logged a count. Failing the whole import over one
            // hand-edited line would lose every other home on the server.
            Path file = fileWith("""
                    players:
                      not-a-uuid:
                        homes:
                          home:
                            world: world
                            x: 1.0
                            y: 2.0
                            z: 3.0
                      66666666-7777-8888-9999-000000000000:
                        homes:
                          base:
                            world: world
                            x: 1.0
                            y: 2.0
                            z: 3.0
                    """);

            assertThat(LegacyHomesFile.read(file))
                    .singleElement()
                    .extracting(LegacyHomesFile.Entry::owner).isEqualTo(BOB);
        }

        @Test
        @DisplayName("a home with no world is stepped over rather than imported as nowhere")
        void aHomeWithNoWorldIsSkipped() throws IOException {
            Path file = fileWith("""
                    players:
                      66666666-7777-8888-9999-000000000000:
                        homes:
                          nowhere:
                            x: 1.0
                            y: 2.0
                            z: 3.0
                          base:
                            world: world
                            x: 1.0
                            y: 2.0
                            z: 3.0
                    """);

            assertThat(LegacyHomesFile.read(file))
                    .singleElement()
                    .extracting(LegacyHomesFile.Entry::name).isEqualTo("base");
        }

        @Test
        @DisplayName("a name the rule would refuse is stepped over rather than stored unreadably")
        void anImpossibleNameIsSkipped() throws IOException {
            // Hand-edited, or written by some other plugin's file that happens to be called
            // homes.yml. Importing it would put a home in the store under a name no command can type.
            Path file = fileWith("""
                    players:
                      66666666-7777-8888-9999-000000000000:
                        homes:
                          'my base':
                            world: world
                            x: 1.0
                            y: 2.0
                            z: 3.0
                          base:
                            world: world
                            x: 1.0
                            y: 2.0
                            z: 3.0
                    """);

            assertThat(LegacyHomesFile.read(file))
                    .singleElement()
                    .extracting(LegacyHomesFile.Entry::name).isEqualTo("base");
        }

        @Test
        @DisplayName("a file that is not YAML at all is nothing to import, not a crash")
        void rubbishIsNotFatal() throws IOException {
            assertThat(LegacyHomesFile.read(fileWith("this: is: not: yaml:\n\t "))).isEmpty();
        }

        @Test
        @DisplayName("a player with an entry but no homes contributes nothing")
        void noHomesIsNothing() throws IOException {
            assertThat(LegacyHomesFile.read(fileWith("""
                    players:
                      66666666-7777-8888-9999-000000000000:
                        name: Bob
                    """))).isEmpty();
        }
    }

    @Nested
    @DisplayName("a name that is capitalised on disk")
    class Normalising {

        @Test
        @DisplayName("it is folded, because the name is the key a command types")
        void namesAreFolded() throws IOException {
            Path file = fileWith("""
                    players:
                      66666666-7777-8888-9999-000000000000:
                        homes:
                          Base:
                            world: world
                            x: 1.0
                            y: 2.0
                            z: 3.0
                    """);

            assertThat(LegacyHomesFile.read(file))
                    .singleElement()
                    .extracting(LegacyHomesFile.Entry::name)
                    .as("the old loader normalised on read too, so a hand-capitalised key has "
                            + "always been reachable as lower case")
                    .isEqualTo("base");
        }
    }
}
