package de.raindancer.modules.farmworld.model;

import de.raindancer.core.world.farm.WorldSet;

import java.time.Duration;
import java.util.List;
import java.util.Optional;

/**
 * One farm world, as everything outside RainsCore sees it.
 *
 * <h2>Why a view rather than passing the {@code WorldSet} around</h2>
 * Because a {@code WorldSet} knows what a farm world <em>is</em> — its three names, its portals, its
 * period — and says nothing about the two things every screen and every command needs first: whether
 * its worlds are actually loaded right now, and how long is left before it is thrown away. Those come
 * from the server and from the recorded times, neither of which belongs in Core's value type.
 *
 * <p>So the store reads both and hands this down. A screen that had to ask the server itself would be
 * a screen that could not be drawn in a test, and "how long until the ground under me disappears" is
 * the one number on the page nobody may be shown wrongly.
 *
 * @param set    the farm world itself, Core's — kept whole rather than copied field by field, so a
 *               component added there does not have to be added here to be reachable
 * @param loaded whether its overworld is loaded. False is ordinary rather than broken: a server that
 *               unloads worlds for maintenance has a farm world nobody can enter for a few minutes
 * @param left   how long until it is made again, or null when there is no schedule and when it has
 *               never been made. Null rather than {@link Duration#ZERO} so that "due now" and "never
 *               due" cannot be confused by arithmetic
 */
public record FarmWorldView(WorldSet set, boolean loaded, Duration left) {

    public FarmWorldView {
        if (set == null) {
            throw new IllegalArgumentException("A farm world view needs the farm world.");
        }
        if (left != null && (left.isNegative() || left.isZero())) {
            // Already past. Carried as "no time left" rather than as a negative, which would print as
            // "made again in -3 minutes" in the one place people look to plan a trip.
            left = null;
        }
    }

    public String name() {
        return set.name();
    }

    /** Every world it has, overworld first. */
    public List<String> worlds() {
        return set.worlds();
    }

    /** Whether it is thrown away on a schedule at all. */
    public boolean isScheduled() {
        return set.regenerateEvery().isPresent();
    }

    /** How often, for the line that says so. */
    public Optional<Duration> every() {
        return set.regenerateEvery();
    }

    /** How long until it is made again. */
    public Optional<Duration> untilRegenerated() {
        return Optional.ofNullable(left);
    }

    /**
     * Whether it is waiting to be made again right now.
     *
     * <p>Only ever true for a farm world that has a schedule. One regenerated by hand is never "due",
     * because there is nothing it is late for.
     */
    public boolean isDue() {
        return isScheduled() && left == null;
    }

    public Optional<Integer> border() {
        return set.border();
    }

    public boolean hasNether() {
        return set.hasNether();
    }

    public boolean hasEnd() {
        return set.hasEnd();
    }
}
